# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

define selenium-recipe =
	$(eval YML=$1)
	$(eval TEST_SCRIPT=$2)
	$(eval CONTAINERS=$3)
	$(eval DBROOT=$(TEST_DATA)/db_$@)
	$(eval LOGFILE=$(TEST_DATA)/ui/$@-$(shell date -u +"%F-%T").log)
	$(eval SELENIUM_COVERAGE_DATA_FILE=$(TESTS_DIRECTORY)/ui/.coverage_$@)
	@set -ex \
		; echo RUNNING SELENIUM TEST $@ \
		; cd .. \
		; EXAMPLEDB=$(EXAMPLEDB) \
		; if [ -n "$4" ] ; then \
			EXAMPLEDB=$4 \
		; fi \
		; echo $(EXAMPLEDB) \
    ; mkdir -p $(shell dirname $(LOGFILE)) \
		; env SECRETSDIR=$(SECRETSDIR) IMAGE=$(BASE_IMAGE):$(VERSION) \
			DBROOT=$(DBROOT) EXAMPLEDB=$${EXAMPLEDB} LOG=$(LOGFILE) LOGSFORCONTAINER=$(CONTAINERS) \
			TEST_SCRIPT=$(TEST_SCRIPT) \
			PROJECT=$(PROJECT) CLEANUP_MODE=$(CLEANUP_MODE) \
			WAITFORCONTAINERS=$(CONTAINERS) \
			$(RUNTEST) $(YML) $(SELENIUM_TEST_COVERAGE_CMD) \
			--data-file=$(SELENIUM_COVERAGE_DATA_FILE) pytest -s $(GENERATE_JUNITXML) \
			$(TEST_SCRIPT) --password=$(SUPASS) 2>&1 | tee -ia $(LOGFILE) \
		; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
		; if [ `grep -c "Traceback" $(LOGFILE)` -ne 0 ] ; then echo "Found error in $@ !"; fi \
		; echo END TEST $@
endef

3d-camera-control-panel: # NEX-T10475
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml, tests/ui/tc_camera_control_panel.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

3d-scene-control-panel: # NEX-T10474
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml, tests/ui/tc_scene_control_panel.py, 'pgserver')
  $(eval SECRETSDIR := $(OLDSECRETSDIR))

3d-ui-calibration-points: # NEX-T10473
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(eval SERVICES := $(strip pgserver web retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/cams.yml)
	$(call selenium-recipe, $(COMPOSE_FILES), tests/ui/tc_3d_ui_calibration_points.py, '$(SERVICES)')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

add-delete-3d-object: # NEX-T10428
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_add_delete_3d_object.py, 'pgserver')

auto-calibration-ui: # NEX-T15710
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(eval SERVICES := $(strip pgserver broker scene retail-video queuing-video autocalibration web))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/autocalibration.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/queuing_video.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web_default.yml:$(COMPOSE)/cams.yml)
	$(call selenium-recipe, $(COMPOSE_FILES), tests/ui/tc_auto_calibration_ui.py, '$(SERVICES)',sample_data/exampledb.tar.bz2)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

bounding-box: # NEX-T10419
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(eval SERVICES := $(strip pgserver web retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/cams.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_bounding_box.py, '$(SERVICES)', true, /run/secrets/browser.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

calibrate-all-sensor-types: # NEX-T10457
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_calibrate_all_sensor_types.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

calibrate-camera-3d-ui-2d-ui: # NEX-T10562
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(eval SERVICES := $(strip pgserver broker scene ntpserv autocalibration web retail-video queuing-video))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/autocalibration.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/queuing_video.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web_default.yml:$(COMPOSE)/cams.yml)
	$(call selenium-recipe, $(COMPOSE_FILES), tests/ui/tc_calibrate_camera_3d_ui_2d_ui.py, '$(SERVICES)')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

camera-deletion: # NEX-T10403
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_camera_deletion.py, 'pgserver')

camera-intrinsics: # NEX-T10415
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_camera_intrinsics.py, 'pgserver')

camera-perspective: # NEX-T10410
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_camera_perspective.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

camera-status: # NEX-T10416
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(eval SERVICES := $(strip pgserver web retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/cams.yml)
	$(call selenium-recipe, $(COMPOSE_FILES), tests/ui/tc_camera_status.py, '$(SERVICES)')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

delete-sensor-scene: # NEX-T10397
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_delete_sensor_scene.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

delete-sensor-mqtt: # NEX-T10432
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_delete_sensor_mqtt.py, 'pgserver scene', true, /run/secrets/controller.auth)
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

delete-sensors: # NEX-T10399
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_delete_sensors.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

different-formats-maps: # NEX-T10392
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_different_formats_maps.py, 'pgserver')

live-view-button: # NEX-T10434
	$(eval SERVICES := $(strip pgserver web retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/cams.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_live_button_works.py, '$(SERVICES)', true)

manual-camera-calibration: # NEX-T10426
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_manual_camera_calibration.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

object-crud: # NEX-T10429
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_object_crud.py, 'pgserver')

persistence: # NEX-T10393
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml)

	$(eval PROJECT := persistence)
	$(eval CLEANUP_MODE := keep_volumes)
	$(call selenium-recipe, $(COMPOSE_FILES), tests/ui/tc_persistence_on_page_navigate.py, 'pgserver:web')

	$(eval PROJECT := persistence)
	$(eval CLEANUP_MODE := full)
	$(call selenium-recipe, $(COMPOSE_FILES), tests/ui/tc_persistence_on_restart.py, 'pgserver:web')

	$(eval SECRETSDIR := $(OLDSECRETSDIR))
	$(eval PROJECT :=)
	$(eval CLEANUP_MODE :=)

restricted-media-access: # NEX-T10494
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_restricted_media_access.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

scene-details: # NEX-T10395
	$(eval SERVICES := $(strip pgserver web retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/cams.yml)
	$(call selenium-recipe, $(COMPOSE_FILES), tests/ui/tc_scene_details.py, '$(SERVICES)')

scenes-summary: # NEX-T10394
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_scenes_summary.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

sensor-area: # NEX-T10401
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_sensor_area.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

sensor-location: # NEX-T10400
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_sensor_location.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

sensor-scene: # NEX-T10396
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_sensor_scene.py, 'pgserver')

show-telemetry-button: # NEX-T10435
	$(eval SERVICES := $(strip pgserver web retail-video scene))
	$(eval COMPOSE_FILES := $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/dlstreamer/retail_video.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml:$(COMPOSE)/cams.yml)
	$(call common-recipe, $(COMPOSE_FILES), tests/ui/tc_show_telemetry_button.py, '$(SERVICES)', true, /run/secrets/controller.auth)

superuser-crud-operations: # NEX-T10418
	$(eval OLDSECRETSDIR := $(SECRETSDIR))
	$(eval SECRETSDIR := $(PWD)/manager/secrets)
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_superuser_crud_operations.py, 'pgserver')
	$(eval SECRETSDIR := $(OLDSECRETSDIR))

upload-3d-glb-file: # NEX-T10425
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_upload_3d_glb_file.py, 'pgserver')

upload-only-3d-glb-files: # NEX-T10433
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/web.yml, tests/ui/tc_upload_only_3d_glb_files.py, 'pgserver')

view-3d-glb-file: # NEX-T10427
	$(call selenium-recipe, $(COMPOSE)/dlstreamer/broker.yml:$(COMPOSE)/ntp.yml:$(COMPOSE)/pgserver.yml:$(COMPOSE)/scene.yml:$(COMPOSE)/web.yml, tests/ui/tc_view_3d_glb_file.py, 'pgserver')
