# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.vdms.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vdms-dep
  labels:
    app: {{ .Release.Name }}-vdms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-vdms
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vdms
        {{ include "releaseLabels" . | indent 8 }}
    spec:
      shareProcessNamespace: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - image: {{ .Values.vdms.image.repository }}/{{ .Values.vdms.image.name }}:{{ .Values.vdms.image.tag }}
          imagePullPolicy: {{ .Values.vdms.image.pullPolicy }}
          name: {{ .Release.Name }}-vdms
          env:
            {{- include "proxy_envs" . | indent 10 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources: {}
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
status: {}
{{- end }}
