# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: scenescape-chart
description: A Helm chart for SceneScape
type: application
version: 1.3.0
appVersion: "2026.0.0-rc1.1"
