---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Updates] Renovate (Tracker Service)"
on:
  schedule:
    # daily
    - cron: "0 2 * * *"

  # allow to manually trigger this workflow
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Run Renovate in dry-run mode (no PR)"
        required: false
        default: false
        type: boolean

permissions: {}

jobs:
  renovate:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: "Get token"
        id: get-github-app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_APP_PEM }}

      - name: "Self-hosted Renovate"
        uses: renovatebot/github-action@3633cede7d4d4598438e654eac4a695e46004420 # v46.1.7
        with:
          configurationFile: .github/renovate.json5
          token: "${{ steps.get-github-app-token.outputs.token }}"
        env:
          LOG_LEVEL: ${{ github.event_name == 'workflow_dispatch' && 'debug' || 'info' }}
          # Dry run if the event is workflow_dispatch AND the dry-run input is true
          RENOVATE_DRY_RUN: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.dry-run == 'true') && 'full' || null }}
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
