---
# SPDX-FileCopyrightText: (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Tests] All Tests"
run-name: "[Tests] All Tests"

on:
  workflow_dispatch:
    inputs:
      cleanup:
        description: "Cleanup before running ALL tests"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      ref:
        description: "SceneScape ref to test against"
        required: false
        default: ""
        type: string
      save_artifacts:
        description: "Save artifacts from tests"
        required: false
        default: true
        type: boolean
      cleanup:
        description: "Cleanup before running ALL tests"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
      - release-*

# Only run at most 1 workflow concurrently per pushed commit
concurrency:
  group: ${{ github.workflow }}-${{ github.sha || github.ref }}-${{ inputs.ref || 'default' }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1
  SUPASS: demo

permissions:
  contents: read

jobs:
  run_functional_tests:
    runs-on: [all]
    name: "Functional Tests"
    permissions:
      packages: write # For using GHCR as cache registry
    timeout-minutes: 120
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Functional Tests
        run: |
          make clean-all
          make run_functional_tests

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_non_functional_tests:
    runs-on: [all]
    name: "Non-Functional Tests"
    permissions:
      packages: write # For using GHCR as cache registry
    timeout-minutes: 20
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Non-Functional Tests
        run: |
          make clean-all
          make run_non_functional_tests

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_metric_tests:
    runs-on: [all]
    name: "Metric Tests"
    permissions:
      packages: write # For using GHCR as cache registry
    timeout-minutes: 40
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Metric Tests
        run: |
          make clean-all
          make run_metric_tests

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_ui_tests:
    runs-on: [all]
    name: "UI Tests"
    permissions:
      packages: write # For using GHCR as cache registry
    timeout-minutes: 90
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run UI Tests
        run: |
          make clean-all
          make run_ui_tests

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_unit_tests:
    runs-on: [all]
    name: "Unit Tests"
    permissions:
      packages: write # For using GHCR as cache registry
    timeout-minutes: 30
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Unit Tests
        run: |
          make clean-all
          make run_unit_tests

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup
